[project]
name = "unity-unite-translator"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pyyaml>=6.0.3",
]

[tool.uv]
dev-dependencies = [
    "black>=24.0",
]
